import path from "path";
import {readFile} from "fs-extra";

const {version} = require('../../../../package.json');


export default async (options) => {

    let readme = await readFile(path.resolve(__dirname, '../../../../README.MD'), 'utf8');

    readme = `This README was generated by @iosio/create-x-project at version: ${version} \n` + readme;

    return {
        file: 'create-x-project.md',
        content: readme
    }
};